name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main", "test"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: LinZhihao-723
          template: classic
          base: header, activity, community, repositories, metadata
          config_animations: yes
          config_timezone: America/New_York
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year         
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, JavaScript, Ruby, Ada
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_days: 30
          plugin_lines: yes
          plugin_calendar: yes
          plugin_calendar_limit: 3
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_traffic: yes